routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
});
 */
Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*
|--------------------------------------------------------------------------
| Student Routes
|--------------------------------------------------------------------------
*/
Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();
Route::resource('/students', App\Http\Controllers\StudentController::class);

/*
|--------------------------------------------------------------------------
| Learnday Routes
|--------------------------------------------------------------------------
*/
Route::get('/learndays/show_deleted', [App\Http\Controllers\LearndayController::class, 'show_deleted'])->name('learndays.show_deleted');
Route::get('/learndays/manage/{learnday}', [App\Http\Controllers\LearndayController::class, 'delete_index'])->name('learndays.delete_attendances');
Route::put('/learndays/restore/{learnday}', [App\Http\Controllers\LearndayController::class, 'restore'])->name('learndays.restore')->withTrashed();
Route::resource('/learndays', App\Http\Controllers\LearndayController::class);

/*
|--------------------------------------------------------------------------
| Attendance Routes
|--------------------------------------------------------------------------
*/

Route::get('/attendances/show_deleted', [App\Http\Controllers\AttendanceController::class, 'show_deleted'])->name('attendances.show_deleted');
Route::get('/attendances/populate_attendance', [App\Http\Controllers\AttendanceController::class, 'populateAttendance'])->name('attendances.populate_attendance');
Route::put('/attendances/mass_update/{learnday}', [App\Http\Controllers\AttendanceController::class, 'massUpdate'])->name('attendances.mass_update');
Route::put('/attendances/restore/{attendance}', [App\Http\Controllers\AttendanceController::class, 'restore'])->name('attendances.restore')->withTrashed();
Route::resource('/attendances', App\Http\Controllers\AttendanceController::class);

app/Models/Learnday.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Learnday extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'date',
        'course_id'    
    ];

    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    public function attendances(): HasMany
    {
        return $this->hasMany(Attendance::class);
    }
}

app/Http/Controllers/LearndayController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use App\Models\Learnday;
use App\Http\Requests\StoreLearndayRequest;
use App\Http\Requests\UpdateLearndayRequest;
use Illuminate\Support\Facades\Auth;

class LearndayController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $this->authorize('viewAny', Learnday::class);

        $learndays = Learnday::all();
        return view('learndays.index', ['learndays' => $learndays]);
    }

    public function delete_index(Learnday $learnday)
    {
        $this->authorize('delete', $learnday);

        return view('learndays.delete_index', ['learnday' => $learnday]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', Course::class);

        $courses = Course::all();
        return view('learndays.create', ['courses' => $courses]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreLearndayRequest $request)
    {
        $this->authorize('create', Course::class);

        $learnday = Learnday::create($request->all());
        $learnday->save();

        return redirect()->route('attendances.populate_attendance', ['learnday_id' => $learnday->id, 'course_id' => $learnday->course_id]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Learnday $learnday)
    {
        $this->authorize('view', $learnday);

        return view('learndays.show', ['learnday' => $learnday]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Learnday $learnday)
    {
        $this->authorize('update', $learnday);

        return view('learndays.edit', ['learnday' => $learnday]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateLearndayRequest $request, Learnday $learnday)
    {
        $this->authorize('update', $learnday);

        $learnday->update($request->all());
        return redirect()->route('learndays.index')->with('success', 'The learnday was updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Learnday $learnday)
    {
        $this->authorize('delete', $learnday);

        foreach ($learnday->attendances()->get() as $key => $attendance) {
            $attendance->delete();
        }

        $learnday->delete();
        return back()->with('success', 'Successfully deleted the learnday: ' . $learnday->name . '.');
    }

    public function show_deleted()
    {
        $this->authorize('viewDeleted', Learnday::class);

        $deleted_learndays = Learnday::onlyTrashed()->get();
        return view('learndays.show_deleted', ['deleted_learndays' => $deleted_learndays]);
    }

    public function restore(Learnday $learnday)
    {
        $this->authorize('restore', $learnday);

        foreach ($learnday->attendances()->withTrashed()->get() as $key => $attendance) {
            $attendance->restore();
        }

        $learnday->restore();
        return back()->with('success', '' . $learnday->name . ' was successfully restored.');
    }

}

resources/views/learndays/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Add a new learningday</h4>
                        <form action={{ route('learndays.store') }} method="POST">
                            @csrf
                            @method('POST')
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    aria-describedby="nameHelp" value="{{ old('name') }}">
                                <div id="nameHelp" class="form-text">Name of the learnday</div>
                            </div>

                            <div class="mb-3">
                                <label for="date" class="form-label">Date</label>
                                <input type="date" class="form-control" id="date" name="date"
                                    aria-describedby="dateHelp" value="{{ old('date') }}">
                                <div id="dateHelp" class="form-text">Learnday's date</div>
                            </div>

                            <select class="form-select" aria-label="Learnday's course" name="course_id" id="course_id"
                                aria-describedby="courseHelp">
                                <option selected disabled>Choose a course</option>
                                @foreach ($courses as $course)
                                    <option value={{ $course->id }} @selected(old('course_id') == $course->id)>{{ $course->name }}</option>
                                @endforeach
                            </select>
                            <div id="courseHelp" class="form-text mb-3">Student's course</div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary text-center">Add</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <div class="col-2"></div>
        </div>
    </div>
@endsection

resources/views/learndays/delete_index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card bg-white">
                    <div class="card-body">
                        <div class="d-flex mb-3">
                            <h4 class="card-title">{{ $learnday->name }} - {{ $learnday->course->name }}</h4>
                            <a name="returnBack" id="returnBack" class="btn btn-success text-end" style="margin-left:auto !important" href="{{ route('learndays.show', ['learnday' => $learnday]) }}" role="button">Return back</a>
                        </div>

                        @if (Session::has('success'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>

                                <strong>Holy guacamole!</strong>
                                <p>{{ Session::get('success') }}</p>
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="mb-3 mt-3">
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                    <strong>Holy guacamole!</strong>

                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        @endif

                        <div class="table-responsive">
                            <table class="table table-light">
                                <thead>
                                    <tr>
                                        <th scope="col">Name</th>
                                        <th scope="col" class="text-left">Birthday</th>
                                        <th scope="col" class="text-center">Status</th>
                                        <th scope="col" class="text-end">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($learnday->attendances as $item)
                                        {{-- {{ dd($item->student) }} --}}
                                        <tr class="">
                                            <td scope="row">{{ $item->student->name }}</td>
                                            <td class="text-left">{{ $item->student->birthdate }}</td>
                                            <td class="text-center">{{ $item->status }}</td>
                                            <td class="text-end">
                                                <form action="{{ route('attendances.destroy', $item) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </form>
                                            </td>
                                            {{-- <td class="text-end"> --}}
                                            {{-- <form action="{{ route('attendances.destroy', $item) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form> --}}
                                            {{-- </td> --}}
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                        {{-- <div class="text-end">
                            <button type="button" class="btn btn-primary text-end" onclick="callFormSubmit();">
                                Save changes
                            </button>
                        </div> --}}

                    </div>

                    {{-- 
                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure to delete this?
                            </div>
                            <div class="modal-footer">
                                <form action="" method="POST" id="deleteModalForm">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" id="deleteDayButton">Yes</button>
                                </form>
    
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            </div>
                          </div>
                        </div>
                    </div>
                    --}}

                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/learndays/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Currently modifying: {{ $learnday->name }}</h4>
                        <form action={{ route('learndays.update', $learnday) }} method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    aria-describedby="nameHelp" value="{{ old('name', $learnday->name) }}">
                                <div id="nameHelp" class="form-text">Learnday's name</div>
                            </div>

                            <div class="mb-3">
                                <label for="date" class="form-label">Date</label>
                                <input type="date" class="form-control" id="date" name="date"
                                    aria-describedby="dateHelp" value="{{ old('date', $learnday->date) }}">
                                <div id="dateHelp" class="form-text">Learnday's date</div>
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-warning text-center">Modify</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <div class="col-2"></div>
        </div>
    </div>
@endsection

resources/views/learndays/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <div class="card bg-white">
                    <div class="card-body">
                        <h4 class="card-title">Title</h4>
                        <div id="calendar"></div>
                    </div>
                </div>


                {{-- <div id="myModal" class="modal fade" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Modal Title</h5>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                <p>This is a simple Bootstrap modal. Click the "Cancel button", "cross icon" or "dark gray area" to close or hide the modal.</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="button" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </div> --}}

                <div class="modal fade" id="calendarEventModal" tabindex="-1" aria-labelledby="calendarEventModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="calendarEventModalLabel">Modal title</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          Choose an action.
                        </div>
                        <div class="modal-footer">
                            <form action="" method="GET" id="editForm">
                                @csrf
                                <button type="submit" class="btn btn-success" id="editButton">Edit</button>
                            </form>

                            <a type="button" class="btn btn-warning" id="attendancesButton" href="">Manage attendances</a>

                            @can('delete', $learndays->first())
                            <form action="" method="POST" id="deleteModalForm">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" id="deleteDayButton">Delete</button>
                            </form>
                            @endcan

                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        


        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                timeZone: 'UTC',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                editable: false,
                dayMaxEvents: true, // when too many events in a day, show the popover
                events: [
                    <?php
                    /* echo "{url: '". route('learndays.show', ['learnday' => $learndays[$i]]) ."', title: '" . $learndays[$i]->name . ' - ' . $learndays[$i]->course->name . "', start: '" . $learndays[$i]->date . "',end: '". $learndays[$i]->date ."',allDay: true},"; */
                    /* echo "{title: '" . $learndays[$i]->name . ' - ' . $learndays[$i]->course->name . "', start: '" . $learndays[$i]->date . "',end: '". $learndays[$i]->date ."',allDay: true},"; */
                    for ($i = 0; $i < count($learndays); $i++) {
                        echo "{id: '". $learndays[$i]->id ."', title: '" . $learndays[$i]->name . ' - ' . $learndays[$i]->course->name . "', start: '" . $learndays[$i]->date . "',end: '". $learndays[$i]->date ."',allDay: true},";
                    } 
                    ?>
                ],
                /* dateClick: function(info) {
                    alert('Date: ' + info.dateStr);
                    alert('Resource ID: ' + info.resource.id);
                }, */
                eventClick: function(info) {
                    /* $("#editForm").attr('action', "{{ route('learndays.edit', '') }}"+'/'+info.event.id) */
                    $("#editForm").attr("action", "{{route('learndays.edit', 'placeholder')}}".replace('placeholder', info.event.id) )
                    $("#attendancesButton").attr('href', "{{route('learndays.show', '')}}"+'/'+info.event.id)
                    $("#deleteModalForm").attr("action", "{{route('learndays.destroy', '')}}"+'/'+info.event.id)
                    $("#calendarEventModalLabel").html(info.event.title + ' - ' + info.event.id);
                    $("#calendarEventModal").modal('show');
                },

                /* eventDragStop: function( info )
                {
                    console.log(info.event.id, info.event.start, info.event.startStr);
                }, */
            });

            calendar.render();
        });
    </script>

@endsection

resources/views/learndays/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <table id="deletedLearndaysTable" class="display">
                    <thead>
                        <tr>
                            <th>Learnday name</th>
                            <th>Learnday date</th>
                            <th>Learnday course</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($deleted_learndays as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->date }}</td>
                                <td>{{ $item->course->name }}</td>
                                <td>
                                    <form action="{{ route('learndays.restore', ['learnday' => $item]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable('#deletedLearndaysTable', {
            responsive: true,
            ordering: false
        });
    </script>
@endsection