routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
});
 */
Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*
|--------------------------------------------------------------------------
| Student Routes
|--------------------------------------------------------------------------
*/
Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();
Route::resource('/students', App\Http\Controllers\StudentController::class);

/*
|--------------------------------------------------------------------------
| Learnday Routes
|--------------------------------------------------------------------------
*/
Route::get('/learndays/show_deleted', [App\Http\Controllers\LearndayController::class, 'show_deleted'])->name('learndays.show_deleted');
Route::get('/learndays/manage/{learnday}', [App\Http\Controllers\LearndayController::class, 'delete_index'])->name('learndays.delete_attendances');
Route::put('/learndays/restore/{learnday}', [App\Http\Controllers\LearndayController::class, 'restore'])->name('learndays.restore')->withTrashed();
Route::resource('/learndays', App\Http\Controllers\LearndayController::class);

/*
|--------------------------------------------------------------------------
| Attendance Routes
|--------------------------------------------------------------------------
*/

Route::get('/attendances/show_deleted', [App\Http\Controllers\AttendanceController::class, 'show_deleted'])->name('attendances.show_deleted');
Route::get('/attendances/populate_attendance', [App\Http\Controllers\AttendanceController::class, 'populateAttendance'])->name('attendances.populate_attendance');
Route::put('/attendances/mass_update/{learnday}', [App\Http\Controllers\AttendanceController::class, 'massUpdate'])->name('attendances.mass_update');
Route::put('/attendances/restore/{attendance}', [App\Http\Controllers\AttendanceController::class, 'restore'])->name('attendances.restore')->withTrashed();
Route::resource('/attendances', App\Http\Controllers\AttendanceController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Student extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'birthdate',
        'course_id',
    ];

    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    public function learndays(): BelongsToMany
    {
        return $this->belongsToMany(Learnday::class, 'attendances');
    }

    public function attendances(): HasMany
    {
        return $this->hasMany(Attendance::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use App\Models\Student;
use App\Http\Requests\StoreStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $this->authorize('viewAny', Student::class);

        $students = Student::all();
        return view('students.index', ['students' => $students]);
    }
    
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $this->authorize('create', Student::class);

        $courses = Course::all();
        return view('students.create', ['courses' => $courses]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreStudentRequest $request)
    {
        $this->authorize('create', Student::class);

        
        $Student = Student::create($request->all());
        $Student->save();

        // Create attendances to the course's learning days
        $course = Course::find($request->course_id);
        $courseLearndays = $course->learningdays()->get();
        
        foreach ($courseLearndays as $key => $learnday) {
            $Student->learndays()->attach($learnday->id, ['status' => 'jelen']);
        }

        return back()->with("success","Student created successfully.");
    }

    /**
     * Display the specified resource.
     */
    public function show(Student $student)
    {
        $this->authorize('view', $student);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Student $student)
    {
        $this->authorize('update', $student);

        $courses = Course::all();
        return view('students.edit', ['student' => $student, 'courses' => $courses]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateStudentRequest $request, Student $student)
    {
        $this->authorize('update', $student);

        // Get the new and old course
        $oldCourse = $student->course;
        $newCourse = Course::find(intval($request->course_id));

        // Get new and old course's learndays
        $oldCourseLearningDays = $oldCourse->learningdays()->get();
        $newCourseLearningDays = $newCourse->learningdays()->get();

        if ($oldCourse != $newCourse)
        {
            foreach ($oldCourseLearningDays as $key => $learnday) {

                // Force delete all attendances that connected to the old course's learning days
                $attendances = $learnday->attendances->where('student_id', $student->id);

                foreach ($attendances as $key => $attendance) {
                    $attendance->delete();
                    \App\Models\Attendance::withTrashed()->where('id', $attendance->id)->forceDelete();
                }
            }

            foreach ($newCourseLearningDays as $key => $learnday) {
                $student->learndays()->attach($learnday->id, ['status' => 'jelen']);
            }

        }

        $student->update($request->all());
        return redirect()->route('students.index')->with( 'success','The student was updated successfully.' );
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Student $student)
    {
        $this->authorize('delete', $student);

        foreach ($student->attendances as $key => $attendance) {
            $attendance->delete();
        }

        $student->delete();
        return back()->with('success','Successfully deleted the student: '.$student->name.'.');
    }


    public function show_deleted(){
        $this->authorize('viewDeleted', Student::class);

        $deleted_students = Student::onlyTrashed()->get();
        return view('students.show_deleted', ['deleted_students'=> $deleted_students]);
    }

    public function restore(Student $student)
    {
        $this->authorize('restore', $student);

        foreach ($student->attendances()->withTrashed()->get() as $key => $deleted_attendance) {
            $deleted_attendance->restore();
        }

        $student->restore();
        return back()->with('success',''.$student->name.' was successfully restored.');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Add a new student</h4>
                        <form action={{ route('students.store') }} method="POST">
                            @csrf
                            @method('POST')
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    aria-describedby="nameHelp" value="{{ old('name') }}">
                                <div id="nameHelp" class="form-text">Student's name</div>
                            </div>

                            <div class="mb-3">
                                <label for="birthdate" class="form-label">Birthdate</label>
                                <input type="date" class="form-control" id="birthdate" name="birthdate"
                                    aria-describedby="birthdateHelp" value="{{ old('birthdate') }}">
                                <div id="birthdateHelp" class="form-text">Student's birthdate</div>
                            </div>

                            <select class="form-select" aria-label="Student's course" name="course_id" id="course_id"
                                aria-describedby="courseHelp">
                                <option selected disabled>Choose a course</option>
                                @foreach ($courses as $course)
                                    <option value={{ $course->id }} @selected(old('course_id') == $course->id)>{{ $course->name }}</option>
                                @endforeach
                            </select>
                            <div id="courseHelp" class="form-text mb-3">Student's course</div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary text-center">Add</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <div class="col-2"></div>
        </div>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Currently modifying: {{ $student->name }}</h4>
                        <form action={{ route('students.update', $student) }} method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    aria-describedby="nameHelp" value="{{ old('name', $student->name) }}">
                                <div id="nameHelp" class="form-text">Student's name</div>
                            </div>

                            <div class="mb-3">
                                <label for="birthdate" class="form-label">Birthdate</label>
                                <input type="date" class="form-control" id="birthdate" name="birthdate"
                                    aria-describedby="birthdateHelp" value="{{ old('birthdate', $student->birthdate) }}">
                                <div id="birthdateHelp" class="form-text">Student's birthdate</div>
                            </div>

                            <select class="form-select" aria-label="Student's course" name="course_id" id="course_id"
                                aria-describedby="courseHelp">
                                <option selected disabled>Choose a course</option>
                                @foreach ($courses as $course)
                                    <option value={{ $course->id }} @selected(old('course_id', $student->course_id) == $course->id)>{{ $course->name }}</option>
                                @endforeach
                            </select>
                            <div id="courseHelp" class="form-text mb-3">Student's course</div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-warning text-center">Modify</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <div class="col-2"></div>
        </div>
    </div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <table id="studentsTable" class="display">
                    <thead>
                        <tr>
                            <th>Student name</th>
                            <th>Student birthdate</th>
                            <th>Student course</th>
                            <th>Actions</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($students as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->birthdate }}</td>
                                <td>{{ $item->course->name }}</td>
                                <td>
                                    <form action="{{ route('students.edit', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('students.destroy', $item) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                                {{-- <td>
                                    <form action="{{ route('students.show', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show</button>
                                    </form>
                                </td> --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable('#studentsTable', {
            responsive: true,
            ordering: true
        });
    </script>
@endsection

resources/views/students/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                        <strong>Holy guacamole!</strong>
                        <p>{{ Session::get('success') }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <table id="deletedStudentsTable" class="display">
                    <thead>
                        <tr>
                            <th>Student name</th>
                            <th>Student birthdate</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($deleted_students as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->birthdate }}</td>
                                <td>
                                    <form action="{{ route('students.restore', ['student' => $item]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        let table = new DataTable('#deletedStudentsTable', {
            responsive: true,
            ordering: false
        });
    </script>
@endsection